name: "Reusable workflow to build JSorolla"

on:
  workflow_call:
    outputs:
      version:
        description: "JSorolla version"
        value: ${{ jobs.build-jsorolla-workflow.outputs.version }}

jobs:
  build-jsorolla-workflow:
    name: Build JSorolla
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.package.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install
      - run: npm run build
      - id: package
        uses: tyankatsu0105/read-package-version-actions@v1
      - uses: actions/upload-artifact@v2
        with:
          name: jsorolla-build
          path: build
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: jsorolla-release
          path: jsorolla-${{ steps.package.outputs.version }}.tar.gz
          retention-days: 1
 