name: "Main Workflow for JSorolla"

on:
  push:
    branches:
      - "develop"
      - "release-*"

jobs:
  build:
    uses: opencb/jsorolla/.github/workflows/build-jsorolla-workflow.yml@develop
    with:
      jsorolla_branch: ${{ github.ref_name }}

  docker:
    needs: build
    # uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    uses: opencb/jsorolla/.github/workflows/docker-jsorolla-workflow.yml@develop
    with: 
      jsorolla_version: ${{ needs.build.outputs.version }}
      jsorolla_branch: ${{ github.ref_name }}
      # cli: python3 ./docker/docker-build.py push --images app --tag ${{ needs.build.outputs.version }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    needs: build
    uses: opencb/jsorolla/.github/workflows/deploy-jsorolla-workflow.yml@develop
    with:
      jsorolla_version: ${{ needs.build.outputs.version }}
    secrets:
      SSH_SWDEV_IP: ${{ secrets.SSH_SWDEV_IP }}
      SSH_SWDEV_USER: ${{ secrets.SSH_SWDEV_USER }}
      SSH_SWDEV_PASSWORD: ${{ secrets.SSH_SWDEV_PASSWORD }}

#  notify:
#    name: Notify private repository
#    runs-on: ubuntu-20.04
#    needs: build
#    steps:
#      - uses: actions/checkout@v2
#      - name: Invoke workflow in a private repo
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: Docker publish
#          ref: ${{ github.event.push.head.ref }}
#          repo: ${{ secrets.JSOROLLA_PRIVATE_REPO }}
#          token: ${{ secrets.ZG_PERSONAL_TOKEN }}
