name: "Reusable workflow to publish JSorolla in DockerHub"

on:
  workflow_call:
    inputs:
      jsorolla_branch:
        type: string
        default: "develop"
      jsorolla_artifact:
        type: string
        default: "jsorolla-build"
      jsorolla_version:
        type: string
        required: true
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
  
jobs:
  docker-jsorolla-workflow:
    name: Publish JSorolla Docker
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.jsorolla_branch }}
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.jsorolla_artifact }}
          path: build
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: python3 ./docker/docker-build.py push --images app --tag ${{ inputs.jsorolla_version }}

